trigger:
- main

pool:
  name: Default
  demands:
  - Agent.Name -equals DESKTOP-4G8JHML

steps:
# Paso 1: Compilar y testear con Maven
- task: Maven@4
  displayName: 'Build con Maven'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    codeCoverageToolOption: 'JaCoCo'

# Paso 2: Verificar que se generó el JAR
- script: |
    echo "Buscando archivos .jar generados:"
    find $(Build.SourcesDirectory) -name "*.jar"
  displayName: 'Verificar .jar generado'

# Paso 3: Copiar JAR al staging para publicación
- task: CopyFiles@2
  displayName: 'Copiar .jar a carpeta drop'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/target/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'
    CleanTargetFolder: true

# Paso 4: Publicar artefacto para otros stages o despliegue
- task: PublishBuildArtifacts@1
  displayName: 'Publicar artefacto: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    
- task: AzureCLI@2
  displayName: 'Desplegar DB usando un pipeline'
  inputs:
    azureSubscription: 'demo-from-azure-devops'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      Variables
      $RESOURCE_GROUP = "NOMBRE_DEL_GRUPO_DE_RECURSOS"
      $LOCATION = "centralus"
      $SQL_SERVER_NAME = "NOMBRE_DEL_SERVIDOR_SQL"
      $ADMIN_USER = "USUARIO_ADMIN"
      $ADMIN_PASSWORD = "CONTRASEÑA_SEGURA"
      $DATABASE_NAME = "myDatabase"

      Write-Output "Creando el grupo de recursos..."
      az group create --name $RESOURCE_GROUP --location $LOCATION

      Write-Output "Creando el servidor SQL..."
      az sql server create `
        --name $SQL_SERVER_NAME `
        --resource-group $RESOURCE_GROUP `
        --location $LOCATION `
        --admin-user $ADMIN_USER `
        --admin-password $ADMIN_PASSWORD

      Write-Output "Configurando reglas de firewall para permitir acceso..."
      az sql server firewall-rule create `
        --resource-group $RESOURCE_GROUP `
        --server $SQL_SERVER_NAME `
        --name AllowMyIP `
        --start-ip-address 192.168.1.88 `
        --end-ip-address 255.255.255.255

      Write-Output "Creando la base de datos SQL..."
      az sql db create `
        --resource-group $RESOURCE_GROUP `
        --server $SQL_SERVER_NAME `
        --name $DATABASE_NAME `
        --service-objective S0

      Write-Output "Despliegue completado exitosamente."

